services:
  web:
    build: .
    depends_on:
      - db
    volumes:
      - .:/app
    ports:
      - "8000:8080"
    env_file:
      - .env

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?Variable not set}
      - POSTGRES_USER=${POSTGRES_USER?Variable not set}
      - POSTGRES_DB=${POSTGRES_DB?Variable not set}
    env_file:
      - .env
    expose:
      - 5432

volumes:
    postgres_data:
