FROM python:3.12.4-alpine3.19

ENV POETRY_HOME="/usr/local" \
    POETRY_VIRTUALENVS_IN_PROJECT=false \
    POETRY_VIRTUALENVS_CREATE=false \
    POETRY_VERSION=1.8.2

RUN apk add curl 
RUN curl -sSL https://install.python-poetry.org | python3 - \
    && poetry --version 

WORKDIR /app
COPY pyproject.toml poetry.lock ./

RUN poetry install --no-root -n

COPY . .

RUN alembic upgrade head

CMD ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8080"]
