"""update note table

Revision ID: 37ac408ad845
Revises: e2b20011c01d
Create Date: 2024-04-18 01:03:54.554541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '37ac408ad845'
down_revision: Union[str, None] = 'e2b20011c01d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('author', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False))
    op.add_column('note', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('note', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_foreign_key(op.f('fk_note_author_user'), 'note', 'user', ['author'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_note_author_user'), 'note', type_='foreignkey')
    op.drop_column('note', 'updated_at')
    op.drop_column('note', 'created_at')
    op.drop_column('note', 'author')
    # ### end Alembic commands ###
