"""update labtest table

Revision ID: e2b20011c01d
Revises: f1d8f0ddc280
Create Date: 2024-04-18 00:22:31.194346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2b20011c01d'
down_revision: Union[str, None] = 'f1d8f0ddc280'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('labtest', 'visit_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('labtest', 'result',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('labtest', 'note',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('labtest', 'note',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('labtest', 'result',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('labtest', 'visit_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
