"""create role table

Revision ID: efa64824ade2
Revises: 3cfbadbaa3ce
Create Date: 2024-03-27 18:27:44.975466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efa64824ade2'
down_revision: Union[str, None] = '3cfbadbaa3ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    roles = op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('name', name=op.f('uq_roles_name'))
    )
    ## Insert data into the roles table
    # meta = sa.MetaData()
    op.bulk_insert(
        # sa.Table('roles', meta, autoload_with=op.get_bind()),
        roles,
        [
            {'id': 1, 'name': 'patient'},
            {'id': 2, 'name': 'lab_tech'},
            {'id': 3, 'name': 'nurse'},
            {'id': 4, 'name': 'doctor'},
        ]
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.add_column('user', sa.Column('role_id', sa.Integer(), nullable=False, server_default="1"))
    op.create_foreign_key(op.f('fk_user_role_id_roles'), 'user', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_user_role_id_roles'), 'user', type_='foreignkey')
    op.drop_column('user', 'role_id')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    # ### end Alembic commands ###
